name: Deploy Azure Storage Account

on:
  push:
    branches: [ postdeplyment_check ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

    - name: Deploy Bicep file
      working-directory: '${{github.workspace}}/actions/bicep'
      run: |
        az deployment group create --name MyDeploymentName --resource-group demo-rg --template-file './storage.bicep' --parameters @parameters.json
        sleep 30  
    - name: Post-deployment check
      working-directory: '${{github.workspace}}/actions/bicep'
      run: |
        # Check the exit status of the Azure CLI commands
        az deployment group show --name MyDeploymentName --resource-group demo-rg --query "properties.provisioningState" --output tsv
  
        # Combine the exit status using '&&' (logical AND)
        if [ $? -eq 0 ]; then
          echo "Deployment succeeded for all resources."
        else
          echo "Deployment failed for one or more resources."
          exit 1
        fi
#