#
name: Deploy Azure Storage Account

on:
  push:
    branches: [ postdeplyment_check ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

    - name: Deploy Bicep file
      working-directory: '${{github.workspace}}/actions/bicep'
      run: |
        az deployment group create --resource-group demo-rg --template-file './storage.bicep' --parameters @parameters.json
    - name: Post-deployment check
      run: |

        az storage account show --name storageaccount15041995 --output tsv
#        --query "provisioningState" --output tsv
#        if [ "$(az storage account show --name storageaccount15041995 --query "provisioningState" --output tsv)" = "Succeeded" ]; then
#          echo "Deployment succeeded"
#        else
#          echo "Deployment failed"
#          exit 1
#        fi
#
#