name: Deploy Storage Account

on:
  push:
    branches:
      - checkov_POC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: Deploy Bicep
        working-directory: '${{github.workspace}}/actions/bicep'
        run: |
          az bicep build --file ./storage.bicep
          az deployment group create --resource-group demo-rg --template-file ./storage.bicep --parameters parameters.json


      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov
        working-directory: '${{github.workspace}}/actions/bicep'
        run: checkov --directory .
          
      - name: Run Checkov
        working-directory: '${{github.workspace}}/actions/bicep'
        run: checkov --directory . --framework bicep --external-checks-dir ../custom-checks/custom_checks.py

