#
name: Deploy Azure Storage Account

on:
  push:
    branches: [ postdeplyment_check ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

    - name: Deploy Bicep file
      working-directory: '${{github.workspace}}/actions/bicep'
      run: |
        az deployment group create --resource-group demo-rg --template-file './storage.bicep' --parameters @parameters.json
    - name: Post-deployment check
      run: |

        # Fetch the provisioningState without specifying the storage account name
        az storage account show --name storageaccount15041995 --query "provisioningState" --output tsv
        provisioning_state=$(az storage account show --name storageaccount15041995 --query "provisioningState" --output tsv)

        # Check the provisioningState and take action accordingly
        if [ "$provisioning_state" = "Succeeded" ]; then
          echo "Deployment succeeded"
        else
          echo "Deployment failed"
          exit 1
        fi


