name: PSRule Check

on:
  push:
    branches:
      - psrule_implementation

jobs:
  # This workflow contains a single job called "build"
  azure_login:
    name: azure_login 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
  
  psrule-check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
    
        - name: Set up PowerShell
          run: |
            pwsh_version='7.2.1'
            pwsh_url="https://github.com/PowerShell/PowerShell/releases/download/v${pwsh_version}/powershell-${pwsh_version}-linux-x64.tar.gz"
            mkdir -p $HOME/pwsh
            curl -L $pwsh_url | tar -xz -C $HOME/pwsh
            echo "export PATH=$HOME/pwsh/pwsh-${pwsh_version}-linux-x64:\$PATH" >> $HOME/.bashrc
            export PATH=$HOME/pwsh/pwsh-${pwsh_version}-linux-x64:$PATH
    
        - name: Install PSRule
          run: pwsh -Command "Install-Module -Name PSRule -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck"
    
        - name: Install Microsoft.Bicep
          run: |
            bicep_version='0.4.1012'
            bicep_url="https://github.com/Azure/bicep/releases/download/v${bicep_version}/bicep-linux-x64"
            curl -L $bicep_url -o $HOME/bicep
            chmod +x $HOME/bicep
            echo "export PATH=$HOME:\$PATH" >> $HOME/.bashrc
            export PATH=$HOME:$PATH
    
        - name: Run PSRule Checks
          run: |
            bicepFiles=$(find . -name "*.bicep" -type f)
            for file in $bicepFiles; do
              pwsh -Command "psrule -Path $file"
            done
              