name: Enforce Branch Naming Convention
on:
  create:
    branches-ignore:
      - 'feature/*'

jobs:
  check_name:
    runs-on: ubuntu-latest
    steps:
      - name: Fail for incorrect branch name
        run: exit 1
