name: Analyze templates
on:
  push:
    branches:
      - psrule_implementation_2
  pull_request:
    branches:
      - psrule_implementation

env:
  PSRULE_AZURE_BICEP_PATH: '/usr/local/bin/bicep'
  PSRULE_OUTPUT_JOBSUMMARYPATH: reports/summary.md
  PSRULE_EXECUTION_INVARIANTCULTURE: Warn
  PSRULE_OUTPUT_AS: Summary
  PSRULE_OUTPUT_FORMAT: Csv

jobs:
  analyze_templates:
    name: Analyze templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Bicep linter
      - name: Install Bicep linter
        run: |
          curl -Lo /usr/local/bin/bicep-linter https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x /usr/local/bin/bicep-linter

      # Analyze Bicep files using the Bicep linter
      - name: Analyze Bicep files
        run: |
          bicep_files=$(find . -type f -name "*.bicep")
          for file in $bicep_files; do
            bicep-linter lint $file
            echo $file
          done
        shell: bash



      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: 'PSRule.Rules.Azure'
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          inputType: 'repository'
          source: '.ps-rule/'
          Baseline: 'Azure.GA_2023_12'