name: Analyze templates
on:
  push:
    branches:
      - psrule_implementation
  pull_request:
    branches:
      - main
env:
  PSRULE_AZURE_BICEP_PATH: '/test/storage.test.bicep'
  PSRULE_OUTPUT_JOBSUMMARYPATH: reports/summary.md
  PSRULE_EXECUTION_INVARIANTCULTURE: Warn
  PSRULE_OUTPUT_AS: Summary
  PSRULE_OUTPUT_FORMAT: Csv
jobs:
  analyze_arm:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Build Bicep file
    - name: Build Bicep file
      run: bicep build $PSRULE_AZURE_BICEP_PATH

    # Analyze Azure resources using PSRule for Azure
    - name: Analyze Azure template files
      uses: microsoft/ps-rule@v2.9.0
      with:
        modules: 'PSRule.Rules.Azure'
        outputFormat: Sarif
        outputPath: reports/ps-rule-results.sarif
        inputType: 'repository'
        source: '.ps-rule/'
        Baseline: 'Azure.GA_2023_12'
