name: Analyze templates
on:
  push:
    branches:
      - psrule_implementation_2
  pull_request:
    branches:
      - psrule_implementation

env:
  PSRULE_AZURE_BICEP_PATH: '/usr/local/bin/bicep'
  PSRULE_OUTPUT_JOBSUMMARYPATH: reports/summary.md
  PSRULE_EXECUTION_INVARIANTCULTURE: Warn
  PSRULE_OUTPUT_AS: Summary
  PSRULE_OUTPUT_FORMAT: Csv

jobs:
  install_bicep:
    name: Install Bicep compiler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bicep compiler
        run: |
          mkdir -p $HOME/bin
          curl -Lo $HOME/bin/bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x $HOME/bin/bicep
          export PATH=$HOME/bin:$PATH
        shell: bash

  compile_bicep:
    name: Compile Bicep files to ARM templates
    runs-on: ubuntu-latest
    needs: install_bicep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Bicep files to ARM templates
        run: |
          find . -type f -name "*.bicep" -print0 | while IFS= read -r -d $'\0' file; do
            bicep build "$file" -o "$(dirname "$file")/$(basename "$file" .bicep).json"
          done
        shell: bash

  analyze_templates:
    name: Analyze ARM template files
    runs-on: ubuntu-latest
    needs: compile_bicep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Analyze ARM template files using PSRule
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: 'PSRule.Rules.Azure'
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          inputType: 'repository'
          source: '.ps-rule/'
          Baseline: 'Azure.GA_2023_12'
